development: &default
  adapter: postgresql
  database: blog_another_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: root
  password: root
test:
  <<: *default
  database: blog_another_test

production:
  <<: *default
  database: blog_another_production 

staging:
  <<: *default
  database: blog_another_staging   